### ISSUE TITLE
Fix event thumbnails for vertical images 

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#100]
This issue only happens with Events that have vertical images. 
Here's an example: 
![screenshot 2017-04-16 11 04 14](https://cloud.githubusercontent.com/assets/25624431/25074375/17f42ba0-2295-11e7-8297-4a04d92a5e1a.png)
![screenshot 2017-04-16 11 04 27](https://cloud.githubusercontent.com/assets/25624431/25074379/24c4bd7c-2295-11e7-98b4-4e6e51054583.png)

**Comment by pfarnach** [comment]
I do see the problem with the thumbnail, but not the event details image (the image appears full width for me).  The issue with the thumbnail is that the `image-wrapper` class has a width of `auto` and a height of `100%`.  If you set both values to `100%`, then the images stretch, and if you reverse the values, you have the same problem but for a majority of the images.  I also tried setting a `min-width` of `150px` but that just stretches the image (the height doesn't seem to compensate).

One half-solution would be to center the image in the circle but there will still be borders.

Does anyone have any thoughts on this?

**Comment by pfarnach** [comment]
Actually we may be able to get around this with cloudinary's transform tools

http://cloudinary.com/documentation/image_transformation_reference

I'll take a whack at it now
