### ISSUE TITLE
Fix date button spacing

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#106]
![screenshot 2017-04-17 20 47 10](https://cloud.githubusercontent.com/assets/25624431/25117819/56db8d02-23af-11e7-9336-06eddaa26893.png)

**Comment by pdw207** [comment]
Also these small issues(left padding and z index)
<img width="223" alt="screen shot 2017-04-20 at 10 17 55 am" src="https://cloud.githubusercontent.com/assets/4714249/25235257/a4ece414-25b2-11e7-8222-3d08723a6548.png">

<img width="355" alt="screen shot 2017-04-20 at 8 57 12 am" src="https://cloud.githubusercontent.com/assets/4714249/25235236/9448c9d4-25b2-11e7-843a-5336fc1301f1.png">

**Comment by pfarnach** [comment]
Fixed with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/119
