### ISSUE TITLE
Make event page buttons work

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#107]
Clicking the event page button on the event details page should open the event's external event page in a new tab.

**Comment by ignu** [comment]
i was looking at this. can reverse engineer the url from the data we currently have with 

    getFacebookUrl(event) {
      const {identifiers} = event;
      if (identifiers[0]) {
        const id = identifiers[0].split(':')[1]
        return `https://facebook.com/events/${id}`
      }
      return null;
    }


**but** this should work as soon as the api returns `base_url`

**Comment by pdw207** [comment]
@ignu  We are getting the eventUrl from the api, no? If not we should because the button would break if we added events from other sources.

**Comment by pdw207** [comment]
@ignu Created a [PR](https://github.com/ResistanceCalendar/resistance-calendar-api/issues/71) on the backend to pass a source attribute defined in the [OSDI docs](https://opensupporter.github.io/osdi-docs/events.html)

**Comment by pfarnach** [comment]
Just checking in -- what's the status of this ticket? I don't see the PR in the backend and it doesn't seem like the URL is coming back in the data.

**Comment by pdw207** [comment]
I created an issue not a PR. Sorry.

**Comment by pfarnach** [comment]
Ah ok -- @aaghevli or @KamillaKhabibrakhmanova is this something one of you can knock out relatively easily?  If not, we can reverse engineer the URL for facebook but would break for other sources, I think

**Comment by dorono** [comment]
Could also break for facebook if other sources get added and FB was no longer the first item in the array, so we'd have to do a string match or something like that :hankey:.

**Comment by aaghevli** [comment]
This has been implemented in the API and should be available by now (had to wait for ETL run).

**Comment by pfarnach** [comment]
Awesome, I see `browser_url` now -- I'll wrap this up today

**Comment by pfarnach** [comment]
@aaghevli any idea why some of them don't have a `browser_url`, like this one? http://localhost:5050/event/58e9a50d74ceb9d94e193e02

@InciteDemocracy if it's something we can't account for and don't have a URL, we should hide the button in the UI right?

**Comment by pfarnach** [comment]
Resolved with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/136

**Comment by pfarnach** [comment]
The PR hasn't been merged yet so I'm re-opening
