### ISSUE TITLE
Fix date selector bug

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#114]
This is a tiny bug! Currently when you click on the date to pop out the calendar, the list view jumps down a few pixels. Also looks like we need to update the styling for the set date button so it looks better when it's selected. 

![screenshot 2017-04-20 11 45 50](https://cloud.githubusercontent.com/assets/25624431/25253958/eff4f580-25be-11e7-8e6c-7435bcb78003.png)

**Comment by InciteDemocracy** [comment]
Also on mobile it is possible to edit the text of the date selector:
![image_uploaded_from_ios-2](https://cloud.githubusercontent.com/assets/25624431/25316240/02faf0e8-27ff-11e7-806b-7d07902332ea.jpg)

**Comment by sdotson** [comment]
@InciteDemocracy it looks like you can edit the text if you're determined on desktop as well.

**Comment by sdotson** [comment]
Doesn't look like there's a simple way to prevent editing the text of the input. Currently we're using react-datepicker and that looks like the default behavior. How do you feel about splitting that out into a new issue?

**Comment by InciteDemocracy** [comment]
This is currently the biggest front end blocker to launching.
