### ISSUE TITLE
Add search by ZIPCODE

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#115]
Can't implement until API resolves this one: https://github.com/ResistanceCalendar/resistance-calendar-api/issues/53

**Comment by aaghevli** [comment]
Hi folks! The API now has this functionality. For example: 

http://resistance-calendar.herokuapp.com/v1/events?distance_postal_code=94110&distance_max=5000

See for more details:
https://github.com/ResistanceCalendar/resistance-calendar-api#queries

See the following for details on the changes:
https://github.com/ResistanceCalendar/resistance-calendar-api/pull/61

**Comment by pfarnach** [comment]
Forget what I said before, I was able to get through a good chunk of this ticket right now and I'll hopefully have a PR for it in the next 24-48 hours.

**Comment by pfarnach** [comment]
Resolved with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/119
