### ISSUE TITLE
Replace Date and Time "PLACEHOLDER" text with properly formatted dates and times

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#116]
Replace dummy dates and timezone placeholders with the real deal :) 

![screenshot 2017-04-20 11 57 31](https://cloud.githubusercontent.com/assets/25624431/25254346/c43908ee-25c0-11e7-86f8-5a745f193125.png)

**Comment by dorono** [comment]
@aaghevli @pdw207 @pfarnach - With regards to getting the timezone - do you know if we are going to be using the location coords to calculate that, or is there going to be a property in the event object with that? (sorry, I've been out of the loop on Slack for the past few days, so perhaps this was already discussed)

**Comment by InciteDemocracy** [comment]
Displaying an event's time zone doesn't seem to be super important. Event times can be displayed in the local time where the event is taking place for v1.

**Comment by aaghevli** [comment]
Hey @dorono, all times should be returned in UTC format, making the use of libraries like moment.js possible to convert to the local timezone client side.

Doing it otherwise requires you to send the lat/long to the server, which complicates caching.

**Comment by dorono** [comment]
@InciteDemocracy - 2 questions:
1) just to confirm - although the mockup shows "6:00 -9:00 PM EST", we can leave off the "EST", right?
2) Are you cool with the fact that we only have a start time coming from the API, so, assuming that we don't have the timezone is the time display, what the user would see in this case would be "6:00 PM". Is this OK?

**Comment by InciteDemocracy** [comment]
Eventually we will def want start time + end time 
Of course start time is the most important time info, so starting with that would be great! Are you sure there is no end time currently included in the API?

**Comment by dorono** [comment]
@InciteDemocracy OK, we now have the end time thanks to @aaghevli. :) Arash is still working on getting us the timezone data we'll need in order to convert the time to the local timezone of the event, but in the meantime, I had 2 more questions for you, @InciteDemocracy 

1.  Is it OK if we keep the "AM" or "PM" after the start time, so instead of, what you have on the mockup, which is "6:00 to 9:00 PM", we'd have "6:00 PM to 9:00 PM"?
2. How likely is it that we will get multi-day events, and if it is at least somewhat likely, did you have any thoughts as to how you'd like to display those, keeping in mind that we would probably need to break down into a new line due to width constraints for mobile portrait view?

**Comment by InciteDemocracy** [comment]
There are a fair number of multi day events...

The simplest fix is to drop the day of the week and the time, and only display the start and end dates:
![screenshot 2017-04-23 08 08 45](https://cloud.githubusercontent.com/assets/25624431/25316090/5f30ca34-27fc-11e7-8074-ceb5722ba5c8.png)

A step up from there would be to include the start time on the first day and the end time on the last day like this: 

![screenshot 2017-04-23 08 08 58](https://cloud.githubusercontent.com/assets/25624431/25316104/8c815918-27fc-11e7-90f8-494dd4ae52ec.png)

**Comment by aaghevli** [comment]
Hey all, dates are now in the returned endpoint. Thanks!

**Comment by dorono** [comment]
@InciteDemocracy - should be doable for the multi-day events, will work on it in the next couple of days.

**Comment by pdw207** [comment]
@dorono I'm assuming we are off by one day due to timezone.

<img width="730" alt="screen shot 2017-04-27 at 9 29 51 am" src="https://cloud.githubusercontent.com/assets/4714249/25485508/2d23d27e-2b2c-11e7-9f74-17e07ed13bf2.png">

**Comment by dorono** [comment]
@pdw207 - Yes, I've got it working locally, just have been away from the project due to my being sidelined with strep. The only thing I have left to do is update the functionality for multi-day events.

**Comment by dorono** [comment]
Will try to work on this today, as I'm starting to feel normal again.

**Comment by dorono** [comment]
@InciteDemocracy - Removed the timezone display requirement from this ticket and broke it off into https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/129, since it's a decent amount of effort, and as we discussed, not 100% essential for MVP.
