### ISSUE TITLE
Update Search Query

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#118]
Example: Searching for “Toomey Town Hall”

Should pull up this event: Our Town Hall With or Without Senator Toomey

    contains(name, “Toomey") or contains(name,  "Town") or contains(name, Hall”)

    $filter=ontains(name, “Toomey") or contains(name,  "Town") or contains(name, "Hall”)

**Comment by pfarnach** [comment]
@aaghevli Can we group terms so we can do things like `(title1 or name1 or desc1) and (title2 or name2 or desc2)` because right now what i have looks like `title1 or name1 or desc1 and title2 or name2 or desc2`

**Comment by aaghevli** [comment]
@pfarnach I think we should be able to do that. I tested via

http://localhost:8000/v1/events?$filter=(contains(title,"Session" or contains(name,"Session")) and (contains(title,"Jeff") or contains(name,"Jeff"))

**Comment by pfarnach** [comment]
Resolved in https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/136

**Comment by pfarnach** [comment]
The PR hasn't been merged yet so I'm re-opening
