### ISSUE TITLE
Custom message where no results given a filter

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#124]
No event in 10 miles of 01002.
<img width="1166" alt="screen shot 2017-04-27 at 9 26 16 am" src="https://cloud.githubusercontent.com/assets/4714249/25485398/cafbc804-2b2b-11e7-9550-49821e496d10.png">

**Comment by InciteDemocracy** [comment]
Custom message should say "We don't see any events for this filter, try setting a wider range"
