### ISSUE TITLE
Display Location Filter outside popup (austin, tx or zip code in screenshots below)

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#125]
Its unclear to a user what the given filter is if hidden in popup. @InciteDemocracy Do we have a design for this?

**Comment by InciteDemocracy** [comment]
Yep, the basic idea is to change the text "set location" to the city or zip that is currently set. 

![screenshot 2017-04-27 11 01 47](https://cloud.githubusercontent.com/assets/25624431/25504270/f6e9d890-2b38-11e7-9ce7-3701d0b9d543.png)

**Comment by pdw207** [comment]
In open PR.

**Comment by InciteDemocracy** [comment]
This is currently merged into the staging app, but it's causing bug #178
