### ISSUE TITLE
Footer Styles

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#134]
@InciteDemocracy The current footer is taking up a lot of space on the screen when the event listing is short.

## Current:
Also no hover on links.
<img width="1041" alt="screen shot 2017-05-02 at 10 52 52 am" src="https://cloud.githubusercontent.com/assets/4714249/25623857/dec3d446-2f25-11e7-914e-43fb1de4350e.png">

## Proposed
Include hover on links

### Desktop
<img width="1087" alt="screen shot 2017-05-02 at 10 54 42 am" src="https://cloud.githubusercontent.com/assets/4714249/25623914/fb7efe80-2f25-11e7-9f3e-11ace7223938.png">

### Mobile

<img width="308" alt="screen shot 2017-05-02 at 10 51 32 am" src="https://cloud.githubusercontent.com/assets/4714249/25623928/01281dd0-2f26-11e7-9257-73ac4de03740.png">

**Comment by InciteDemocracy** [comment]
I also prefer something like this.
