### ISSUE TITLE
Proposed Compact SubHeader

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#135]
Because we have a lot of additional space on desktop can I suggest we move the calendar select to the same row as the other filters?
<img width="1181" alt="screen shot 2017-05-02 at 10 31 45 am" src="https://cloud.githubusercontent.com/assets/4714249/25624068/5754fd9a-2f26-11e7-9179-e540078171fe.png">

**Comment by InciteDemocracy** [comment]
Yep, that was the plan originally...it got put in it's own row when the mobile version got done.
