### ISSUE TITLE
Style change if current day is selected second time

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#150]
![error](https://cloud.githubusercontent.com/assets/4714249/25878306/b9dfdd6e-34f7-11e7-80cf-29f896a74f1d.gif)

**Comment by pdw207** [comment]
Now if you select date and reselect the date disappears

**Comment by InciteDemocracy** [comment]
This is issue is specific to the date that is "today

Steps to recreate issue:

1. Select a random date. 
2. Select today's date.
