### ISSUE TITLE
Hovers gives False indication the row is clickable

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#154]
Hover on a row and seems to indicate a link but only the title brings you to the details page

**Comment by InciteDemocracy** [comment]
I agree this is confusing, we should either make the whole event card clickable or remove the hover. Either way is ok with me. The objection to making the whole card clickable was that you can't select the text of the event, but you still can't do that currently without going to the details page.

**Comment by pfarnach** [comment]
I'll remove the hover effect.  Agreed that making the whole thing clickable was problematic
