### ISSUE TITLE
Add Redux to site

### ISSUE THREAD

**Issue by pfarnach** [ResistanceCalendar/resistance-calendar-frontend#16]

**Comment by pdw207** [comment]
for pagination: https://github.com/PCreations/redux-paginator

**Comment by ignu** [comment]
I can grab this.

Anyone have opinions on https://github.com/erikras/ducks-modular-redux or https://github.com/skellock/reduxsauce?

I'm not a huge fan of just `/actions` and `/reducers` directories. I'd rather just a user component with action creators/reducers for the user in the same file.
