### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by pfarnach** [ResistanceCalendar/resistance-calendar-frontend#18]

**Comment by jktravis** [comment]
I'll see if I can get this working.

**Comment by jktravis** [comment]
Apparently, I don't have the access needed to get this setup. 

    You don't have sufficient rights to enable this repo on Travis. 
    Please contact the admin to enable it or to receive admin rights yourself.

**Comment by pfarnach** [comment]
cc: @InciteDemocracy

**Comment by jktravis** [comment]
It looks like there's already a [.travis.yml](https://github.com/ResistanceCalendar/resistance-calendar-frontend/blob/master/.travis.yml) file in the repo. I don't think there's much else to do besides logging into Travis and turning it on.

**Comment by pdw207** [comment]
done!
