### ISSUE TITLE
Add RSVP counters to events

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#185]
The API has RSVP data for FB events
We can display it in list view like this: 
![screenshot 2017-07-12 11 29 29](https://user-images.githubusercontent.com/25624431/28141130-fd8078fe-66f6-11e7-8e6c-79b7a3083ad0.png)

And also on event details pages like this:
![screenshot 2017-07-12 11 44 06](https://user-images.githubusercontent.com/25624431/28141248-7599b594-66f7-11e7-96ca-1bddd5861c97.png)

**Comment by ignu** [comment]
looking at this one now.
