### ISSUE TITLE
Iphone Filter Button

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#200]
Iphone 6

<img width="262" alt="screen shot 2017-10-10 at 8 34 09 am" src="https://user-images.githubusercontent.com/4714249/31386740-e54a9e28-ad95-11e7-8f0c-ea80501b7c70.png">

Also when you click you open the location select. Input fields are not positioned correctely. If you click below an input it is highlighted.

**Comment by dorono** [comment]
@pdw207 I know it would have been good to implement the new design, but I was short on time, and just wanted to get that mobile bug fixed asap, as it's a pretty bad one. I'll close this out, and hopefully we can get to the new filter location design ticket soon.
