### ISSUE TITLE
Decision on stateless component style

### ISSUE THREAD

**Issue by jktravis** [ResistanceCalendar/resistance-calendar-frontend#27]
It's my understanding that using anonymous functions as stateless components can cause debugging issues since there is no name attached to the function. Instead, the suggestion is to just export a named function. 

So instead of doing this:

```javascript
    const ExpandableForm = ({ onExpand, expanded, children }) => {
```

It's recommended to do this:

```javascript
function ExpandableForm ({onExpand, expanded, children}) {
```

Should we decide as a group to try and avoid them or does it just not matter?

**Comment by dentemple** [comment]
My vote is to stick with the ES6 syntax for the Stateless Functional Components (SFCs).  (And, to be honest, I've only ever seen the ES6 syntax recommended for SFCs).

```jsx
const MyComponent = (props) => { ... }
```

The purpose behind SFCs is to create a clear delineation between smart components and dumb components, and to make these delineations as clear as possible even when doing a quick scan.  

As an explicit function, it may not be as immediately obvious that the line refers to a component and not a function to be called later.  Which seems to be the reason for the recommendation.

There's not really a "debugging" issue per se, the function will just show up as _anonymous_ in a console log, but between 1) React Developer Tools, 2) good test coverage with Jest/Enzyme, and 3) a functional approach to component composition, I've never had an issue with determining where components are breaking.

**Comment by pfarnach** [comment]
Closing this issue since it doesn't seem like there's more to say
