### ISSUE TITLE
Download Google fonts and host locally

### ISSUE THREAD

**Issue by dorono** [ResistanceCalendar/resistance-calendar-frontend#31]

**Comment by dentemple** [comment]
Link to the design discussion regarding the typography: https://github.com/ResistanceCalendar/design/issues/9

**Comment by dorono** [comment]
After doing some research, it seems like self-hosting these fonts might not really help, and could actually hurt the site's performance. @dentemple @pdw207 @pfarnach @sdotson - do you guys have any thoughts on this? 

At the very least, we could make this a phase II thing (even though it's not rocket surgery).

**Comment by sdotson** [comment]
I think you might be right. I saw an article [here](https://www.keycdn.com/blog/web-font-performance/) comparing different approaches. Google [still recommends](https://developers.google.com/fonts/faq#should_i_host_fonts_on_my_own_websites_server) using their links.

**Comment by dorono** [comment]
Yeah, in the spirit of "draining the swamp" of TODO's and get the MVP out the door quicker, I think I'm going to close this out, we can always revisit this later if it turns out to be an issue after all, which I doubt.
