### ISSUE TITLE
Create global stylesheet for shared styles and replace hard-coded global CSS values with the variables (a la Sass)

### ISSUE THREAD

**Issue by dorono** [ResistanceCalendar/resistance-calendar-frontend#32]

**Comment by dentemple** [comment]
I was looking into this, and it seems that Next.js is opinionated towards the inline approach to CSS.

Which, I suppose, just means that there's some extra webpack configuration necessary to meet this requirement.

(If you attempt to import it now, you'll get a 'module load' error)

**Comment by dentemple** [comment]
Updated my comment above.  The style-jsx library inherently allows for globally-scoped css.

**Comment by pfarnach** [comment]
Was this taken care of in the switch over to SCSS/CSS modules?  (looking specifically at the `src/style` files.
