### ISSUE TITLE
Apply styling to event list on homepage

### ISSUE THREAD

**Issue by dorono** [ResistanceCalendar/resistance-calendar-frontend#42]

**Comment by pdw207** [comment]
@dorono What additional styles are needed to close this?

**Comment by dorono** [comment]
I created this a while back, I believe it's done, but @pfarnach can confirm - Pat - are we done with this one?

**Comment by pfarnach** [comment]
Yep.  It seems like the styling is mostly there and improvements will be made in separate issues
