### ISSUE TITLE
Make entire event card clickable

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#56]
Currently you need to click on the event title to get to the event details page. The entire event card should be a button that takes users to the event details.

**Comment by sdotson** [comment]
Hi, I saw this issue and decided to have a crack at it.

**Comment by pfarnach** [comment]
Hi @sdotson, make sure to assign the ticket to yourself (so we don't duplicate efforts) and close it when it's been merged in.

Resolved in https://github.com/ResistanceCalendar/resistance-calendar-frontend/commit/96de41679a1ef55a4ddb49fba7fdc21dcf0cf2c1 and https://github.com/ResistanceCalendar/resistance-calendar-frontend/commit/3d153f56db0c548175af6937568f0293c5aa7ed4

**Comment by sdotson** [comment]
@pfarnach, will do!
