### ISSUE TITLE
Set maximum length of event description in desktop list view to 250 characters

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#58]
Some events have very long descriptions, we want to display a truncated version of this ideally with ellipsis at the end of it. Tockify does 200 characters let's try 250.

**Comment by pfarnach** [comment]
Resolved in https://github.com/ResistanceCalendar/resistance-calendar-frontend/commit/e6fe5bee4e7b78703d95be5c1b11111a79773c7a
