### ISSUE TITLE
Make events list full width on desktop for larger screens

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#60]
Currently the desktop view is full width up to a point, and then it adds in red bars on the sides. We want the white to stretch full span from side to side for larger screens too.

**Comment by pfarnach** [comment]
Does this mean remove the max-width on the main container?  It's pretty traditional to have a max width on containers otherwise you have content spanning the whole screen which hurts readability.  Would increasing the current max width help?

**Comment by pfarnach** [comment]
Resolved in https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/70/commits/2023eb6d875b54b5d38272fbdcf9e8d788f8ced4
