### ISSUE TITLE
Remove Button Focus outlines for chrome.

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#61]
Maybe button:focus {outline:0;} will do the trick for getting the blue line around the buttons/search box to go away.

**Comment by pfarnach** [comment]
I'm happy to remove the focus outline.  In reading a bit about it, some people have strong feelings about it being a bad practice from an accessibility/usability perspective which is something to be aware of

**Comment by pfarnach** [comment]
Resolved in https://github.com/ResistanceCalendar/resistance-calendar-frontend/commit/e6fe5bee4e7b78703d95be5c1b11111a79773c7a
