### ISSUE TITLE
Update pop up Calendar Menu

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#67]
Enlarge (close to full width on mobile)
Add day boxes 
Add larger back/forward icon buttons. 
Make day abbreviations 3 letters, all caps. 
Remove box outline
Add drop shadow

![screenshot 2017-03-30 11 39 23](https://cloud.githubusercontent.com/assets/25624431/24527385/8ae8c2e8-153d-11e7-9a29-dd544359323a.png)

**Comment by dorono** [comment]
@caitlynl22 - Are you going to be doing this as part of your work on the nav? (https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/69) A lot of this is already done, but def needs some css updates as per @InciteDemocracy and possibly some pixel-pushing/visual cleanup.

**Comment by caitlynl22** [comment]
@dorono Absolutely, I'm working on that tonight and will have a solid 4-6 hours (or more) to work on it tomorrow.

**Comment by dorono** [comment]
@caitlynl22 Very cool, just want to make sure we don't overlap. There are a couple more issues that are header/filter-related that I wanted to check on as well, but in the meantime, I can work on non-header/filter stuff. If we just keep the Github issues up to date, then we shouldn't have to worry about the overlap. Thanks!

**Comment by dorono** [comment]
@caitlynl22 assigning this over to you!

**Comment by pfarnach** [comment]
Down the road we may want to make the calendar full width, but for now this is fine
