### ISSUE TITLE
Update pop up Location Menu

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#68]
Enlarge and center (close to full width on mobile)
Add triangular tab to upper right to indicate connection to "location button"
Improve spacing of elements

![screenshot 2017-03-30 12 20 02](https://cloud.githubusercontent.com/assets/25624431/24528648/3b78e2be-1543-11e7-9f14-55f6e57c3f35.png)

**Comment by dorono** [comment]
@caitlynl22 - Are you going to be doing this as part of your work on the nav? (https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/69)

**Comment by pfarnach** [comment]
Seems like this is necessary for the MVP -- I'm making it a P1

**Comment by InciteDemocracy** [comment]
This appears to be fixed now (tested on iphone), currently the only issue is a styling bug with the cancel button on mobile
![img_1133](https://cloud.githubusercontent.com/assets/25624431/25766702/c1c49738-318f-11e7-97b1-2961f7fb52b3.PNG)

**Comment by pfarnach** [comment]
Ok I have a PR out to fix this (https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/143)
