### ISSUE TITLE
Update Nav layout on Mobile

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#69]
![screenshot 2017-03-30 12 32 16](https://cloud.githubusercontent.com/assets/25624431/24529018/f9dca99c-1544-11e7-8bd5-5a478bec90e0.png)

**Comment by dorono** [comment]
@InciteDemocracy @caitlynl22 Hey guys, I've been working on the HTML/CSS part of doing this - but is someone already working on that? Not sure if this issue is for the design or if it's for the actual code.
