### ISSUE TITLE
Convert Add Event form to Pop up

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#72]
Currently the add event form appears full page. We want to make it appear as a popup menu connected to the add events button.

![screenshot 2017-03-31 14 27 59](https://cloud.githubusercontent.com/assets/25624431/24573439/c896e3d6-161e-11e7-8d81-b10c3802b26a.png)

**Comment by ignu** [comment]
Should there still be a route to `/add-event`?

And should this still be a modal on mobile?
