### ISSUE TITLE
Implement social media sharing functionality on social media buttons

### ISSUE THREAD

**Issue by dorono** [ResistanceCalendar/resistance-calendar-frontend#73]
In the SocialBtns component, we are currently just passing in hyperlinks that simply take you to the event, as opposed to opening up Facebook or Twitter's native sharing dialogue. 

* For Facebook, we need to do it here:
https://developers.facebook.com/docs/javascript/examples (we'll need to create a Facebook App in the resistancecalendar FB account)
* For Twitter: https://dev.twitter.com/web/tweet-button

**Comment by sdotson** [comment]
This sounds like fun. Happy to take a crack at it if there's someone who can create a Facebook App in the resistancecalendar FB account and hand me the application id. If that might be a while, I could create a dummy app with my account for testing purposes.

**Comment by sdotson** [comment]
Oh my mistake. looks like this is already being worked on https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/63

**Comment by dorono** [comment]
@sdotson I just updated the https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/63 to reflect that that ticket was just for popup behavior and responsive layout work, so feel free to have at this one!

**Comment by dorono** [comment]
@InciteDemocracy - Maybe you can create the FB app for the FB sharing button that @sdotson is thinking of implementing. There's no coding involved in creating the app, it's just filling out a form on developers.facebook.com (https://developers.facebook.com/docs/apps/register). Let me know if you need more info on that.

**Comment by InciteDemocracy** [comment]
I'd be happy to help with facebook app setup, we have an existing FB app, should we create a second separate one for this?

**Comment by pdw207** [comment]
@dorono @InciteDemocracy I don't think you need a separate app. Maybe provide access to whomever takes this issue.

**Comment by dorono** [comment]
Hey there @sdotson! Assigned this over to you, just to make sure we avoid having any time wasted with duplicate work.

**Comment by sdotson** [comment]
Sounds good.

**Comment by InciteDemocracy** [comment]
This is a small detail blocking launch: 

![screenshot 2017-05-24 09 15 51](https://cloud.githubusercontent.com/assets/25624431/26434340/fd18ac16-40a3-11e7-924f-925232c2ded2.png)

Once the app lives in a domain other than heroku the facebook sharing integration needs to be updated to work with that URL. 

@sdotson maybe you can take a look :) 

Currently we are testing here:
www.incitedemocracy.org

**Comment by sdotson** [comment]
I think the www.incitedemocracy.org domain needs to be added to the whitelisted domains in the app settings. This would need to be done by a person who has access to the settings on facebook.com. Do you know who might have those privileges? I'd be glad to do it myself but someone would need to grant me access first.

**Comment by pdw207** [comment]
Where are we on this? Is this done?

**Comment by dorono** [comment]
@InciteDemocracy @pdw207 I just tried this on the live site w/both FB and Twitter, and it seems to be working (unless @sdotson thinks otherwise?), so I believe that this should be marked as done. 

However, the event's photo is not currently being shared, so I believe we should create a separate ticket to make that happen, IMO.

**Comment by sdotson** [comment]
Yep. I think this should be marked as done if it's working on the live site.

**Comment by InciteDemocracy** [comment]
@dorono I agree, let's close this issue and create a separate ticket for including event images.
