### ISSUE TITLE
Move add event form to event listing as modal on desktop

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#80]

**Comment by dorono** [comment]
@pdw207 There was talk of holding off on doing this for now just to get the site live quicker, since the page is already working as is (albeit not as slick as with the modal). Whaddyafink?

**Comment by ignu** [comment]
isn't this a dupe of https://github.com/ResistanceCalendar/resistance-calendar-frontend/issues/72

(also i had a question on that)

**Comment by pdw207** [comment]
It is a duplicate. Going to close this one. @dorono I agree with you but already started this so will just finish it.
