### ISSUE TITLE
Scroll events list only

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#84]
Currently people could find themselves at the bottom of a very long list of events, We could either add a "back to top" shortcut button or make the nav stick to the top of the window. 

![screenshot 2017-04-09 12 04 43](https://cloud.githubusercontent.com/assets/25624431/24841296/27f60a0a-1d1d-11e7-8aa2-55d1223fa33b.png)

**Comment by dorono** [comment]
I am actually working on this as part of my work om the header

**Comment by dorono** [comment]
@caitlynl22 Here's another one I was curious about, since it falls within the realm of the header/filter stuff you were working on. Were you thinking you might take this one on?

**Comment by dorono** [comment]
@caitlynl22 assigning this over to you as part of the header/filter stuff, feel free to unassign as needed, of course, just want to make sure nobody starts on this if you're already working on it.

**Comment by pdw207** [comment]
@caitlynl22 Can you give an update or we will remove you from this ticket?

**Comment by caitlynl22** [comment]
@pdw207 Sorry Paul, somehow I missed this before. I have a lot more time now and am planning to finish this today.
