### ISSUE TITLE
Display future events

### ISSUE THREAD

**Issue by InciteDemocracy** [ResistanceCalendar/resistance-calendar-frontend#89]
Examples:

When no date is set display all events happening from today -->

When a date is set display all events happening from that day -->

Current implementation:

When no date is set, all events are displayed including past events
When a date is set, only events from that day are displayed.

**Comment by dorono** [comment]
Gonna be out for a while, unassigning myself since it's the weekend and don't want to prevent anyone else from working on this.

**Comment by pfarnach** [comment]
Resolved with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/109
