### ISSUE TITLE
Specify sort order for events

### ISSUE THREAD

**Issue by aaghevli** [ResistanceCalendar/resistance-calendar-frontend#92]
See the docs for the API for examples:

https://github.com/ResistanceCalendar/resistance-calendar-api#ordering

Specifically by start date (default order is asc):
http://resistance-calendar.herokuapp.com/v1/events?$orderby=start_date
http://resistance-calendar.herokuapp.com/v1/events?$orderby=start_date%20desc

**Comment by dorono** [comment]
Gonna be out for a while, unassigning myself since it's the weekend and don't want to prevent anyone else from working on this.

**Comment by dorono** [comment]
Gonna be out for a while, unassigning myself since it's the weekend and don't want to prevent anyone else from working on this.

**Comment by pfarnach** [comment]
@InciteDemocracy what sort order do we want for this?  Do we want to set a default, or expose the option to the user with a toggle button or something?  (obviously the former would be simpler to implement)

**Comment by InciteDemocracy** [comment]
For starters we just need events to be in chronological order. When you arrive at the site events happening today will be displayed at the top, scrolling down them gets you to events happening tomorrow, etc. (V2 can include sorting by proximity and attendance etc.)

**Comment by pfarnach** [comment]
Resolved with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/109
