### ISSUE TITLE
Can't search for text string and enter date

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#95]

**Comment by pfarnach** [comment]
This is related to a bug in the ODATA library we're using on the backend.  @aaghevli submitted a PR to them, but I'm not sure if it's been accepted yet.

**Comment by aaghevli** [comment]
That is correct @pfarnach and @pdw207. I can probably just publish my own npm artifact and use that in RCAPI since I don't think we will get the PR accepted anytime soon.

**Comment by InciteDemocracy** [comment]
We need to be able to search and filter by both location and time simultaneously. Currently we seem to be able to search while filtering for location but not time.

**Comment by aaghevli** [comment]
That bug has been fixed by me publishing my own fix to npm. Has this been attempted again? I am oway on vacation so can check, but this should be fixed

**Comment by pfarnach** [comment]
@aaghevli I just checked and it seems like this isn't working.  The call below returns an event that's before the selected starting date

`https://resistance-calendar.herokuapp.com/v1/events?page=0&per_page=25&$orderby=start_date%20desc&$filter=contains(title,%20%27ngozi%27)%20or%20contains(name,%20%27ngozi%27)%20or%20contains(description,%20%27ngozi%27)%20and%20start_date%20gt%202017-05-12`

**Comment by aaghevli** [comment]
I think you want an additional parens around the text clause? 

This returns nothing:
```
https://resistance-calendar.herokuapp.com/v1/events?page=0&per_page=25&$orderby=start_date%20desc&$filter=(contains(title,%20%27ngozi%27)%20or%20contains(name,%20%27ngozi%27)%20or%20contains(description,%20%27ngozi%27))%20and%20start_date%20gt%202017-05-12
```

While the gt flipped to lt returns 2 events:

```
https://resistance-calendar.herokuapp.com/v1/events?page=0&per_page=25&$orderby=start_date%20desc&$filter=(contains(title,%20%27ngozi%27)%20or%20contains(name,%20%27ngozi%27)%20or%20contains(description,%20%27ngozi%27))%20and%20start_date%20lt%202017-05-12
```

**Comment by pfarnach** [comment]
Thanks, that solved two issues in one!

**Comment by pfarnach** [comment]
Resolved in https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/136

**Comment by pfarnach** [comment]
The PR hasn't been merged yet so I'm re-opening
