### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by pdw207** [ResistanceCalendar/resistance-calendar-frontend#96]
Favicon is blurry, also support all browsers

**Comment by InciteDemocracy** [comment]
This Zip contains updated favicons in various sizes. 
Let me know if we need any additional dimensions or formats
![apple-icon-114x114](https://cloud.githubusercontent.com/assets/25624431/25074914/f2401b54-22a2-11e7-9628-edc0d0c5c4a5.png)
 

[RC.ico.zip](https://github.com/ResistanceCalendar/resistance-calendar-frontend/files/924626/RC.ico.zip)
