### ISSUE TITLE
Location based searching

### ISSUE THREAD

**Issue by aaghevli** [ResistanceCalendar/resistance-calendar-frontend#99]
The server can support some basic proximity based searcher. See PR below. We can discuss making the API more versatile (city / zip / etc) as part of this work.

https://github.com/ResistanceCalendar/resistance-calendar-api/pull/59

**Comment by pfarnach** [comment]
@InciteDemocracy does it make sense to move forward with zipcode-only filtering?  If so, it makes sense to me that it should happen on the server so we don't have to ship all the zipcodes with client code

**Comment by aaghevli** [comment]
I think so. Zip code search plus distance should not be too hard.

**Comment by pfarnach** [comment]
Resolved with https://github.com/ResistanceCalendar/resistance-calendar-frontend/pull/119
